import './global.css'
import { ThemeProvider } from '@mui/material'
import { theme } from '../utils/theme'
import { EmotionCacheProvider } from '../context/EmotionCacheContext'

export const metadata = {
  title: 'Welcome to ui-web',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <EmotionCacheProvider>
      <ThemeProvider theme={theme}>
        <html lang="en">
          <body>{children}</body>
        </html>
      </ThemeProvider>
    </EmotionCacheProvider>
  )
}
