import './global.css'
import { ThemeProvider } from '@mui/material'
import { theme } from '../utils/theme'
import { EmotionCacheProvider } from '../context/EmotionCacheContext'
import { SnackbarProvider } from '../context/SnackbarContext'
import { AuthNavigationProvider } from '../context/AuthNavigationContext'
import CustomSnackbar from '../components/custom-snackbar/custom-snackbar'
import { AuthProvider } from '../context/AuthContext'

export const metadata = {
  title: 'Ticket Avengers',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <EmotionCacheProvider>
          <ThemeProvider theme={theme}>
            <SnackbarProvider>
              <AuthProvider>
                <CustomSnackbar />
                <AuthNavigationProvider>{children}</AuthNavigationProvider>
              </AuthProvider>
            </SnackbarProvider>
          </ThemeProvider>
        </EmotionCacheProvider>
      </body>
    </html>
  )
}
