# Deploy changes to the `develop` branch in to the dev environment
name: Deployment (shared workflow)
run-name: Deploy to ${{ inputs.env_name }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      env_name:
        description: 'The name of the environment to be deployed'
        required: true
        type: string
    secrets:
      aws_account_id:
        description: Account ID for AWS
        required: true
  
# concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency: merge-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.env_name }}

    steps:
      # ref: https://github.com/marketplace/actions/checkout
    - name: Checkout code
      uses: actions/checkout@v3

    # ref: https://github.com/marketplace/actions/setup-node-js-environment
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # ref: https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.aws_account_id }}:role/GitHub
        aws-region: us-east-1

    - name: Install dependencies
      run: npm ci
      env:
        CI: true

    # ref: https://github.com/marketplace/actions/serverless
    - name: Deploy to environment
      run: npm run sst:deploy -- --stage ${{ inputs.env_name }}
