###
# Deploys the changes of a particular PR to a preview environment in the "dev" AWS account.
###
name: PR Preview Env - Set Up

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason for manual trigger'
        required: true
        default: 'Re-run past failed build'

  # pull_request:
  #   types: [opened, synchronize]

# concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency: merge-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # ref: https://github.com/marketplace/actions/checkout
    - name: Checkout code
      uses: actions/checkout@v4

    # ref: https://github.com/marketplace/actions/setup-node-js-environment
    - name: Install node (includes yarn)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      env:
        CI: true

    # ref: https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.DEV_AWS_ACCOUNT_ID }}:role/GitHub
        aws-region: us-east-1

    - name: Deploy to PR preview environment
      run: npm run sst:deploy -- --stage PR-${{ github.event.pull_request.number }}